module Matches
  module Scoring
    class PerspectiveCheck
      # requester - Matches::Scoring::Values::MatchParticipant
      # teams - something generated by submatch#submatch_participants_to_match_participants_value
      attr_reader :requester, :teams

      def initialize(requester:, teams:)
        @requester = requester
        @teams = teams
      end

      def call
        requester_team, competitor_team = teams

        if competitor_team.map(&:id).include?(requester.id)
          [competitor_team, requester_team]
        else
          [requester_team, competitor_team]
        end
      end
    end
  end
end
